spring:
  application:
    name: florescence-music
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${SERVER_PORT}
mybatis-plus:
  mapper-locations: classpath:cn/fluorescent/fluorescentmusic/dao/impl/*.xml
  type-enums-package: cn.fluorescent.fluorescentmusic.enmu
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true
  type-aliases-package: cn.fluorescent.fluorescentmusic.entity
weixin:
  mp:
    app:
      id: ${MP_APP_ID}
      secret: ${MP_APP_SECRET}
tencent:
  cos:
    app-id: ${COS_ID}
    bucket-name: ${COS_BUCKET}
    region-id: ${COS_REGION}
    secret-id: ${COS_SECRET_ID}
    secret-key: ${COS_SECRET_KEY}
    base-url: ${COS_BASE_URL}
