@startuml
participant Actor
Actor -> ArtistController : register
activate ArtistController
create BizException
ArtistController -> BizException : new
activate BizException
BizException --> ArtistController
deactivate BizException
create Artist
ArtistController -> Artist : new
activate Artist
Artist --> ArtistController
deactivate Artist
ArtistController -> ArtistService : savaArtist
activate ArtistService
ArtistService -> ArtistServiceImpl : savaArtist
activate ArtistServiceImpl
ArtistServiceImpl -> ArtistDao : registeredArtist
activate ArtistDao
ArtistDao --> ArtistServiceImpl
deactivate ArtistDao
ArtistServiceImpl --> ArtistService
deactivate ArtistServiceImpl
ArtistService --> ArtistController
deactivate ArtistService
create BizException
ArtistController -> BizException : new
activate BizException
BizException --> ArtistController
deactivate BizException
create UserRole
ArtistController -> UserRole : new
activate UserRole
UserRole --> ArtistController
deactivate UserRole
create BizException
ArtistController -> BizException : new
activate BizException
BizException --> ArtistController
deactivate BizException
ArtistController -> ResponseResult : success
activate ResponseResult
create ResponseResult
ResponseResult -> ResponseResult : new
activate ResponseResult
ResponseResult --> ResponseResult
deactivate ResponseResult
ResponseResult --> ArtistController
deactivate ResponseResult
return
@enduml