@startuml
participant Actor
Actor -> ArtistController : search
activate ArtistController
ArtistController -> ResponseResult : success
activate ResponseResult
create ResponseResult
ResponseResult -> ResponseResult : new
activate ResponseResult
ResponseResult --> ResponseResult
deactivate ResponseResult
ResponseResult --> ArtistController
deactivate ResponseResult
return
@enduml