@startuml
participant Actor
Actor -> ArtistController : delete
activate ArtistController
create BizException
ArtistController -> BizException : new
activate BizException
BizException --> ArtistController
deactivate BizException
create BizException
ArtistController -> BizException : new
activate BizException
BizException --> ArtistController
deactivate BizException
ArtistController -> ResponseResult : success
activate ResponseResult
create ResponseResult
ResponseResult -> ResponseResult : new
activate ResponseResult
ResponseResult --> ResponseResult
deactivate ResponseResult
ResponseResult --> ArtistController
deactivate ResponseResult
return
@enduml